spring:
  application:
    default: CONFIG-DEFAULT
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-wth-eureka: true
    service-url:
      defaulZone: http://localhost:8761/eureka
